language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda create -y --quiet --name gda_env --file requirements-linux-py2.txt
    else
      conda create -y --quiet --name gda_env --file requirements-linux-py.txt
    fi
  - source activate gda_env
script:
  - python setup.py build_ext --inplace
  - py.test
  - python setup.py build_doc_html
  - python setup.py build_doc_latex
  - cd doc_build/latex/latex
  - pdflatex GDAToolbox
  - pdflatex GDAToolbox
  - pdflatex GDAToolbox
  - makeindex GDAToolbox
  - pdflatex GDAToolbox
  - pdflatex GDAToolbox
  - source deactivate
